run_cmd: merge stderr into stdout and use event_receiver
Splitting stderr and stdout messes up the output in apk cmd:

  localhost# apk add dummy
  ERROR: unable to select packages:
  dummy (no such package):
    required by: world[dummy]

  localhost# apk add dummy >/dev/null
  ERROR: unable to select packages:

So raised exception doesn't print details about the error.

Also:

* replace newlines and tabs in run_cmd

* move EventReceiver to a separate class